name: Hello Shivani Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Hello from Shivani! 🎉 GitHub Actions is working!"
